name: 'Flutter Action'

inputs:
  channel:
    description: 'The Flutter build release channel'
    required: false
    default: 'stable'
  version:
    description: 'The Flutter version to install'
    required: false
    default: 'any'
  arch:
    description: 'The architecture of Flutter SDK executable (x64 or arm64)'
    required: false
    default: 'x64'

runs-on: ubuntu-latest

steps:
  - name: Flutter Setup
    run: './.github/actions/runner/setup.sh ${{ inputs.channel }} ${{ inputs.version }} ${{ inputs.arch }}'