name: CI/CD with Flutter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: actions/setup-node@v2 # Use the setup-node action to set up Node.js (required for Flutter)
        with:
          node-version: 14
          
      - name: Install Flutter
        
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PWD/flutter/bin:$PATH"
        shell: bash
      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: flutter-pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
      - name: Build Flutter App
        run: flutter test # Adjust this command to match your build needs