name: Dart

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.5.1
      
      - run: dart pub global activate fvm
      - run: fvm install 3.13.3
      - run: fvm use 3.13.3
      - run: fvm flutter test