name: CI/CD with Flutter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: ./ # Use the relative path to your custom action directory
        with:
          flutter-version: '3.13.3' # Specify the desired Flutter version
          release-channel: 'stable' # (Optional) Specify the release channel (default: 'stable')
          cache-sdk: true # (Optional) Cache the Flutter SDK for faster builds (default: true)
          sdk-architecture: 'x64' # (Optional) Specify the SDK architecture (default: 'x64')

