name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Flutter Setup
        run: ./.github/actions/flutter-setup/setup.sh
        with:
          channel: stable # Specify the Flutter channel
          version: any    # Specify the Flutter version
          arch: x64   

      - name: Cache Flutter packages
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: Get Packages
        run: flutter pub get
        
      - name: Run Analayze
        run: flutter analyze
        
      - name: Run tests
        run: flutter test

      - name: Generate code coverage report
        run: flutter test --coverage
