name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Flutter Setup
      
        uses: ./.github/actions/runner
        with:
            channel: stable
            version: any
            arch: x64
    
      - name: Cache Flutter packages
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: Get Packages
        run: flutter pub get
        
      - name: Run Analayze
        run: flutter analyze
        
      - name: Run tests
        run: flutter test

      - name: Generate code coverage report
        run: flutter test --coverage
