name: Flutter CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
      # id of job, a string that is unique to the "jobs" node above.
      drive:
        # Creates a build matrix for your jobs. You can define different
        # variations of an environment to run each job in.
        strategy:
          # A set of different configurations of the virtual environment.
          matrix:
            device:
            - "iPhone 8 (13.1)"
            - "iPhone 11 Pro Max (13.1)"
          # When set to true, GitHub cancels all in-progress jobs if any matrix job
          # fails.
          fail-fast: false
        # The type of machine to run the job on.
        runs-on: macOS-latest
        # Contains a sequence of tasks.
              
        steps:
          - name: "List all simulators"
            run: "xcrun xctrace list"
          - name: "Start Simulator"
            run: |
              UDID=$(
                xcrun xctrace list |
              awk \
                -F ' *[][]' \
                -v 'device=${{ matrix.device }}' \
                '$1 == device { print $2 }'
              )
    
              xcrun simctl boot "${UDID:?No Simulator with this name found}"
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Set up Dart
            uses: dart-lang/setup-dart@v1.5.1
    
          - name: Cache Flutter and pub dependencies
            uses: actions/cache@v2
            with:
              path: |
                ~/.pub-cache
                ~/.pub
                ~/.fvm
              key: ${{ runner.os }}-flutter-pub-${{ hashFiles('**/*.yaml') }}
    
          - name: Install and use FVM
            run: |
              dart pub global activate fvm
              fvm install 3.13.3
              fvm use 3.13.3
    
          - name: Run Flutter tests
            run: fvm flutter test
          - name: "Run Flutter Driver tests"
            run: "flutter drive --target=test_driver/app.dart"
      # Deploy code to staging environment
    