on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: actions/setup-flutter@v2
        with:
          flutter-version: stable
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Run Flutter Tests
        run: flutter test