name: CI/CD with Flutter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PWD/flutter/bin:$PATH"
      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: flutter-pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
      - name: Build and Test Flutter App
        shell: true
        run: |
          flutter pub get
          flutter test